### ISSUE TITLE
Allow restricting this to certain HTTP verbs

### ISSUE THREAD

**Issue by sfudeus** [containous/plugin-blockpath#14]
A helpful addition to this is the ability to configure a list of HTTP verbs for each regex path which allows to configure which verbs to block for specific paths. There are use cases where only certain verbs need to be blocked. 

Are you willing to take a PR implementing this? 

A sample config for this might look like:
```
testData:
  blockentries:
  - regex:
    - "^/foo(.*)"
    methods:
    - POST
    - GET
  - regex:
    - "^/foo-blockallmethods(.*)"

```
